name: Github Pages Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm ci
      - name: Create Build
        run: npm run build --if-present

      - name: Deploy to github pages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run ng deploy --base-href=/AI-Adventures/ --repo=https://github.com/ShrootBuck/AI-Adventures.git --name=ShrootBuck --email=${{ secrets.EMAIL }}
